### ISSUE TITLE
Change .umbrel to .runcitadel ?

### ISSUE THREAD

**Issue by nolim1t** [runcitadel/core#1]
Should we change .umbrel to .runcitadel ?

https://github.com/runcitadel/core/blob/35e50381bca34e552f634f59e10ecd81defae1d8/scripts/configure#L81

**Comment by AaronDewes** [comment]
Only `.citadel`, but I'll do that soon.

**Comment by AaronDewes** [comment]
Fixed by https://github.com/runcitadel/core/commit/d11199ed11c29979841e637e2ed9cd2eb7e361dc
