### ISSUE TITLE
Wordpress App

### ISSUE THREAD

**Issue by nullcount** [runcitadel/core#19]
Currently, connecting a public wordpress instance to your home node requires port forward. 

With BTCPay on the same host as Wordpress, the connection could be automated.

Thoughts on a wordpress app? It could use a custom docker image with woocommerce and btcpayserver plugins installed/preconfigured.

Self-hosted ecommerce with non custodial LN checkout using your own node. Tor by default.

**Comment by AaronDewes** [comment]
Sorry for the delay in response, a beta WordPress app is available in Citadel 0.0.3.
