### ISSUE TITLE
Some problems when I tried run in ubuntu server

### ISSUE THREAD

**Issue by igor-rodrigues2017** [runcitadel/core#20]
I needed change 2 files: 

- scripts/start

I changed the way to run docker-compose (**git diff**):

@@ -111,7 +111,7 @@ echo
 echo
 echo "Starting Docker services..."
 echo
**-docker compose up --detach --build --remove-orphans || {**
**+docker-compose up --detach --build --remove-orphans || {**
   echo "Failed to start containers"
   exit 1
 }

- and the ENV UNSAFE_REMOVE_CORS_CHECK in docker-compose.yml (**git diff**):

@@ -156,7 +156,7 @@ services:
       REDIS_PASSWORD: freedom
       REDIS_IP: $REDIS_IP
       REDIS_PORT: 6379
**-UNSAFE_REMOVE_CORS_CHECK: true
+UNSAFE_REMOVE_CORS_CHECK: 1**
     networks:
       default:
         ipv4_address: $MANAGER_IP
@@ -183,7 +183,7 @@ services:
       LND_HOST: ${LND_IP}
       JWT_PUBLIC_KEY_FILE: /jwt-public-key/jwt.pem
       DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://citadel.local"}
**-UNSAFE_REMOVE_CORS_CHECK: true
+UNSAFE_REMOVE_CORS_CHECK: 1**
     networks:
       default:
         ipv4_address: $MIDDLEWARE_IP

- and install: 
sudo apt install -y python3-dacite python3-semver

Thanks guys! I hope that this comment help you.

**Comment by AaronDewes** [comment]
`docker-compose` is outdated and not supposed to be used with Citadel, it breaks a lot of things. You don't need to install it 

Citadel automatically installs `docker compose`, a modern replacement for `docker-compose` on startup. However, it seems like you had a few dependencies missing, so it didn't work. We have a list of all dependencies included in this guide: https://runcitadel.space/x86

I recommend uninstalling Citadel, undoing your modifications and then installing it again with all dependencies installed.

**Comment by igor-rodrigues2017** [comment]
nice! Thanks a lot! a I'll install again.
