### ISSUE TITLE
E: Unable to locate package runcitadel

### ISSUE THREAD

**Issue by Lightning8Count** [runcitadel/core#57]
Trying to install citadel core, but got the following message

`sudo apt install gh repo clone runcitadel/core
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package clone
E: Unable to locate package runcitadel
`

can anyone help please thanks

**Comment by WilliamConnatser** [comment]
Hi, it looks like you are trying to install Citadel? We have a guide you can follow here:  https://runcitadel.space/x86. You need to use `git` to "clone" Citadel- it is not an installable Linux package.

**Comment by Lightning8Count** [comment]
> git

Thanks for the prompt response, i was using that guide and this was what I got when i used git:
`git clone https://github.com/runcitadel/core.git ~/citadel
Command 'git' not found, but can be installed with:
sudo apt install git
`

**Comment by WilliamConnatser** [comment]
Please read the responses. It is telling you what you need to do! `sudo apt install git`

**Comment by Lightning8Count** [comment]
`sudo apt install git https://github.com/runcitadel/core.git
[sudo] password for citadel: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package https://github.com/runcitadel`

Hence the title of this issue

**Comment by WilliamConnatser** [comment]
You are still not running the right command. Please read my reply and the guide again.
